import { randomUUID } from 'node:crypto'

/** Lifecycle status of an agent-creation job. */
export type AgentStatus = 'queued' | 'processing' | 'ready' | 'failed'

/** A single conversational turn stored for history reference. */
export interface ChatTurn {
  role: 'user' | 'assistant'
  text: string
}

/**
 * Represents an in-progress or completed agent-creation job.
 *
 * Jobs are stored in memory and keyed by their UUID. Once the background
 * process completes successfully the job holds the ElevenLabs `agentId` that
 * the frontend uses to start voice conversations.
 */
export interface AgentJob {
  /** Unique job identifier (UUID). */
  id: string
  /** Normalised arXiv paper identifier. */
  arxivId: string
  /** Current lifecycle status. */
  status: AgentStatus
  /** Paper title populated after arXiv metadata is fetched. */
  title?: string
  /** System-prompt instructions generated by Gemini from the paper abstract. */
  instructions?: string
  /** ElevenLabs Conversational AI agent ID created for this paper. */
  agentId?: string
  /** Human-readable error message when `status === 'failed'`. */
  error?: string
  /** Ordered chat history for this session. */
  history: ChatTurn[]
}

const jobs = new Map<string, AgentJob>()

/**
 * Creates and persists a new agent job in the `queued` state.
 *
 * @param arxivId - Normalised arXiv paper identifier.
 * @returns The newly created job.
 */
export function createJob(arxivId: string): AgentJob {
  const job: AgentJob = {
    id: randomUUID(),
    arxivId,
    status: 'queued',
    history: [],
  }

  jobs.set(job.id, job)

  return job
}

/**
 * Retrieves a job by its ID.
 *
 * @param jobId - UUID of the job to retrieve.
 * @returns The job, or `undefined` if it does not exist.
 */
export function getJob(jobId: string): AgentJob | undefined {
  return jobs.get(jobId)
}

/**
 * Applies a partial update to an existing job.
 *
 * @param jobId   - UUID of the job to update.
 * @param updates - Partial job fields to merge.
 * @returns The updated job, or `undefined` if the job was not found.
 */
export function updateJob(jobId: string, updates: Partial<AgentJob>): AgentJob | undefined {
  const job = jobs.get(jobId)

  if (!job) {
    return undefined
  }

  const next = {
    ...job,
    ...updates,
    history: updates.history ?? job.history,
  }

  jobs.set(jobId, next)

  return next
}

/**
 * Appends a single chat turn to a job's history.
 *
 * @param jobId - UUID of the job to update.
 * @param turn  - The chat turn to append.
 * @returns The updated job, or `undefined` if the job was not found.
 */
export function appendChat(jobId: string, turn: ChatTurn): AgentJob | undefined {
  const job = jobs.get(jobId)

  if (!job) {
    return undefined
  }

  const next = {
    ...job,
    history: [...job.history, turn],
  }

  jobs.set(jobId, next)

  return next
}
